config/routes.rb
Rails.application.routes.draw do
  get 'practices/kanji'
	get 'practices/result' => "practices#result"
	post 'practices/add' => "practices#add"
	delete 'practices/delete/:id' => "practices#delete"
	
  get 'weedocs/index' => "weedocs#index"
  get 'weedocs/add'
	post 'weedocs/add' => "weedocs#create"
	get 'weedocs/delete'
	get 'weedocs/search' => "weedocs#search"
  delete 'weedocs/delete/:id' => "weedocs#delete"
	
  resources :blogs do
	  resources :comments
  end
	
  devise_for :users
	root "posts#index"
  get 'posts/index'
  get 'posts/new' => "posts#new"
  post 'posts/create' => "posts#create"
  get 'posts/show/:id' => "posts#show"
  get 'posts/edit/:ids' => "posts#edit"
  post 'posts/update/:id' => "posts#update"
  #get 'posts/destroy/:id' => "posts#destroy"
	delete 'posts/destroy/:id' => "posts#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	
	post "blogs/:blog_id/likes/create" => "likes#create"
	post "blogs/:blog_id/likes/destroy" => "likes#destroy"
	
	# post하면 토큰이 필요하네. get하면 https에서 http로 자동으로 가버리네?
	#get "blogs/:blog_id/likes/create" => "likes#create"
	#get "blogs/:blog_id/likes/destroy" => "likes#destroy"
	
	
end

app/models/blog.rb
class Blog < ApplicationRecord
	#, :dependent => :destroy 이거 넣으면 글 지워질때 댓글도 같이 지워지네. 이거 없으면 글 삭제 안되고 에러남.
	has_many :comments, :dependent => :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :chu]
  # GET /blogs
  # GET /blogs.json
	
	#20220220 form으로 delete하려고하면 토큰 에러나네
	protect_from_forgery :only => ["delete"]
	
  def index
    #@blogs = Blog.all
	#@blogs = Blog.all.order(created_at: "ASC")
	@blogs = Blog.all.order(:created_at)
	 
	  #page20220305
	  @pages = params[:pages].to_i
	  
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
	  #20220221로그인안한 사람 비번 확인
	  if @blog.passwd == params[:pw_check]
	  else
		  #redirect_to :back
		  redirect_to blogs_path
	  end
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    #20220221 삭제전 패스워드 확인 
	respond_to do |format| 
	  if @blog.passwd == params[:pw_check] 
		@blog.destroy
    	format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      	format.json { head :no_content }
	  else #추가부분
		format.html { redirect_to @blog, alert: 'Failed to delete.' }
        format.json { render :show, @blog.errors, status: :unprocessable_entity }
	  end 
    end
  end


	
	##
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      	#20220220작성자 추가
		#params.require(:blog).permit(:title, :description)
		params.require(:blog).permit(:title, :description, :writer, :passwd)	
    end
	
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "제목 タイトル" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description, "내용 内容" %>
    <%= form.text_area :description, size: "100x2" %>
  </div>

<% if user_signed_in? %>
  	<div>
	  글쓴이作成者: <%= current_user.email %>
		<%= form.hidden_field :writer, :value => current_user.email %>
		<%= form.hidden_field :passwd, :value => "LoginUser" %>
	</div>

<% else %>
  <div class="field">
    <%= form.label :writer, "글쓴이作成者" %>
    <%= form.text_field :writer %>
  </div>

  <div class="field">
    <%= form.label :passwd, "password" %>
    <%= form.text_field :passwd %>
  </div>
<% end %>



  <div class="actions">
    <%= form.submit "작성(作成)"%>
  </div>
<% end %>

app/views/blogs/_header.html.erb
<% if user_signed_in? %>
	<p><%= current_user.email.split("@")[0] %>様, hello &nbsp;
	<%= link_to "logout", destroy_user_session_path, method: :delete %></p>
<% else %>

<% end %>
<p>	<%= link_to "Home", root_path %></p>
<hr size="2px">

app/views/blogs/edit.html.erb
<h1>Editing</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', @blog %> |
<%= link_to 'Main', blogs_path %>

app/views/blogs/index.html.erb
<%= render 'header' %>

<style>
	@import url('https://fonts.googleapis.com/css2?family=Cute+Font&display=swap');
	
	td{
		padding-left: 15px;
		padding-right: 15px;
		font-family: 'Cute Font', cursive;
		font-size: 20px;
		word-break: break-word;
		
	}
	th{
		padding-top: 10px;
		padding-left: 15px;
		padding-right: 15px;
		padding-bottom: 10px;
		font-family: 'Cute Font', cursive;
		font-size: 30px;
	}
	a{
		text-decoration: none;
	}
	#show {
		
		width: 700px;
		height: 50%;
		border: 5px double brown;
		background-color: skyblue;
		display: inline-block;
		text-align: left;
	}
	
	#show > #pages{
		text-align: center;
		padding: 10px;
	}
	
	#show2{
		display: none;
	}

	.diary{
		text-align: center;
	}
	
</style>


<p id="notice"><%= notice %></p>

<h1>한문장일기(1文章日記）</h1>

<% if user_signed_in? %>
<%= link_to '글쓰기(書き込み)', new_blog_path, class: 'btn', style: 'font-size:14px;' %>
<% else %>
<%= link_to "login해서 글쓰기(loginして書き込み)", user_session_path, style: 'color:green; font-size:14px;' %>
&nbsp; &nbsp; &nbsp; &nbsp; 
<%= link_to '그냥글쓰기(書き込み)', new_blog_path, class: 'btn', style: 'color:green; font-size:14px;' %>	
<% end %>

<hr />

<div class="diary">

	<div id="show">
		<table>
			<tr>
			  <th width=10px>No.</th>
			  <th width=280px><center>Title</center></th>
			  <th width=140px><center>작성자</center></th>
			  <th width=50px>date</th>
			  <th></th>
			</tr>
		
			<% page = @pages %>
			<% page_size = 10 %>
			<% p = page * page_size %>
			<% for i in (0...page_size) %> 
			  <% if @blogs[i+p] %>
			  <tr>
				<td><%= i + p + 1 %></td>
				<td><font size=5px><b><%= link_to "#{@blogs[i+p].title[0..15]}", @blogs[i+p] %><%= "..." if @blogs[i+p].title.length > 10 %></b></font> <font color="palevioletred" size=3px> [<%= @blogs[i+p].comments.count %>]</font> </td>
				<td><center><%= @blogs[i+p].writer %></center></td>
				<td><font size=2px><%= @blogs[i+p].created_at.strftime "%m月%d日" %></font></td>
				<td> 💕<b><%= Like.where(blog_id: @blogs[i+p].id).count %></b></td>
			  </tr>
			  <% end %>
			<% end %>

		 </table>
		
		<div id="pages">
		<% for i in (1..(@blogs.size/page_size.to_f).ceil) %>
			<% if i-1 == page %>
			<%= i %>
			<% else %>
			<b><%= link_to "【#{i}】", blogs_path(pages: i-1) %></b>
			<% end %>
		<% end %>	
		</div>

		
		
		<br>
	</div>
	 
	<div id="show2">
		<table>
			<tr>
			  <th>No.</th>
			  <th>Title</th>
			  <th>작성자</th>
			  <th>date</th>
			  <th></th>
			</tr>

			<% @blogs.each_with_index do |blog, index| %> 
			  <tr>
				<td><%= index+1 %></td>
				<td><font size=5px><b><%= link_to "#{blog.title[0..10]}", blog %><%= "..." if blog.title.length > 10 %></b></font> <font color="palevioletred" size=3px> [<%= blog.comments.count %>]</font> </td>
				<td><%= blog.writer %></td>
				<td><font size=2px><%= blog.created_at.strftime "%m月%d日" %></font></td>
				<td> 💕<b><%= Like.where(blog_id: blog.id).count %></b></td>
				<!--
				<td><%= link_to 'Show', blog %></td>
				<td><%= link_to(blog) do %>
					<%= blog.title %>
					<% end %>
				  </td>
				-->
			  </tr>
			<% end %>
		  
		</table>
		

		<br>
	</div>

	
</div>

app/views/blogs/new.html.erb
<h2>１문장에 오늘을 담아봅시다.</h2>
<h2>１文章で今日をまとめましょう。</h2>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><font color="red"><%= alert %></font></p>

<% if user_signed_in? %>
	<% login_ID = current_user.email %>
	<% login_PID = current_user.id %>
<% else %>
	<% login_ID = "" %>
	<% login_PID = 0 %>
<% end %>


<p>
	<% if Like.find_by(user_id: login_PID , blog_id: @blog.id) %>
	<%= link_to("💕", "/blogs/#{@blog.id}/likes/destroy", {method: "post"}) %>
	<% else %>
	<%= link_to("🖤", "/blogs/#{@blog.id}/likes/create", {method: "post"}) %>
	<% end %>
	<%= Like.where(blog_id: @blog.id).count %>
</p>


<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <%= @blog.description %>
</p>
<hr />

<p>
<%= link_to 'Home', blogs_path %>
<br />
<%= link_to 'Back', :back %>	
&nbsp;&nbsp;
<% if @blog.writer == login_ID %>
	<%= link_to 'Edit', edit_blog_path(@blog, pw_check: @blog.passwd) %>
	&nbsp;&nbsp;
	<!--%= link_to 'Delete', @blog, method: :delete, data: { confirm: 'Are you sure?' } %-->
	<form name="passcheck" action="/blogs/<%= @blog.id %>" method="post" onsubmit="return confirm('Are you sure?');">
		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="pw_check" value="<%= @blog.passwd %>">
		<input type="submit" value="Delete">
	</form>
<% else %>
	작성자作成者：<%= @blog.writer %>
	
	<% if @blog.passwd == "LoginUser" %>
	<% else  %>
		<form name="passcheck" action="/blogs/<%= @blog.id %>" method="post">
			<input type="hidden" name="_method" value="DELETE">
			Password : <input type="text" id="pw_check" name="pw_check">	
			<input type="submit" value="Delete">
			<input type="button" onclick="return check()" value="Edit">
			
		</form>

		<script type="text/javascript">
			function check(){
				var p1 = document.getElementById("pw_check").value;
				var p2 = <%= @blog.passwd %>;
				//머여...자바스크립트는 소스보기에서 데이터가 보여버리네. 이걸 숨기려면? 요건 나중에하고, 우선은 냅두고,  
				//delete은 데이터를 안 보이는 곳controller으로 가져가서  처리함
				if( p1 != p2 ){
					alert("비번 달라~ password 違う~");
					return false;
				} else{
					//alert("bingo!");
					//return true;
					location.href="/blogs/<%= @blog.id %>/edit?pw_check="+p1
				}
			}
		</script>
	<% end %>
<% end %>

</p>
<hr />

<h3>
	comment
</h3>
    <% @blog.comments.each_with_index do |comment, index| %>
      <div>
		  <p>
			  <span><%= index+1 %>.</span>
			  <%= comment.writer %>
			  <%= comment.comment %>
			  <% if comment.writer == login_ID %>
			  <span><%= link_to "delete", [comment.blog, comment], method: :delete, data: { confirm: "delete?"} %></span>
			  <% end %>
		  </p>
		  
 	 </div>
    <% end %>



<hr />


<%= render 'comments/form' %>