config/routes.rb
Rails.application.routes.draw do
  get 'practices/kanji'
	get 'practices/result' => "practices#result"
	post 'practices/add' => "practices#add"
	delete 'practices/delete/:id' => "practices#delete"
	
  get 'weedocs/index' => "weedocs#index"
  get 'weedocs/add'
	post 'weedocs/add' => "weedocs#create"
	get 'weedocs/delete'
	get 'weedocs/search' => "weedocs#search"
  delete 'weedocs/delete/:id' => "weedocs#delete"
	
  resources :blogs do
	  resources :comments
  end
	
  devise_for :users
	root "posts#index"
  get 'posts/index'
  get 'posts/new' => "posts#new"
  post 'posts/create' => "posts#create"
  get 'posts/show/:id' => "posts#show"
  get 'posts/edit/:ids' => "posts#edit"
  post 'posts/update/:id' => "posts#update"
  #get 'posts/destroy/:id' => "posts#destroy"
	delete 'posts/destroy/:id' => "posts#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	
	post "blogs/:blog_id/likes/create" => "likes#create"
	post "blogs/:blog_id/likes/destroy" => "likes#destroy"
	
	# post하면 토큰이 필요하네. get하면 https에서 http로 자동으로 가버리네?
	#get "blogs/:blog_id/likes/create" => "likes#create"
	#get "blogs/:blog_id/likes/destroy" => "likes#destroy"
	
	
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	protect_from_forgery :only => ["create"]
	#protect_from_forgery except: :create
	
  def index
	  #@posts = Post.all
	  @posts = Post.all.order(:created_at)
  end

  def new
  end

  def create
	if user_signed_in?
		writer = current_user.email
	elsif
		if params[:post_pw] == "1234" && params[:scret] == "3" && params[:language] == "on"
			writer = "aaa@aaa.aaa"
		else
			writer = "wrong"
		end
	end
	  
	  if writer == "aaa@aaa.aaa"
	  	post=Post.create(title: params[:title], content: params[:content], writer: writer)
	  	redirect_to "/posts/show/#{post.id}"
	  end
	  
  end

  def show
	  @post = Post.find(params[:id])
  end

  def edit
	  #if user_signed_in? && current_user.email == "aaa@aaa.aaa"
	  	@post = Post.find(params[:ids])
	  #elsif

	  #end
  end

  def update
	  post = Post.find(params[:id])
	  post.update(title: params[:title], content: params[:content])
	  redirect_to "/posts/show/#{post.id}"
  end

  def destroy
	  if user_signed_in?
		post = Post.find(params[:id])
	  	if post.writer == current_user.email
		  post.destroy
		  redirect_to "/posts/index"
	  	else
		end
		  
	  end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">
    
<style>
p {
            color: darkgreen;
            text-align: center;
            line-height:200%;
            /*
			text-decoration: line-through;
			*/

            font-size: 48px;
            font-weight: bold;
            font-family: 'Nanum Pen Script', cursive;
}
</style>

<font size="10" color="red">impossible</font> <br />
<p>
	비밀을 풀어야 쓸 수 있단다. 개킹받쥬?
</p>

<%= link_to "back", posts_index_path %>

app/views/posts/destroy.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">
    
<style>
	@import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Jua&family=Nanum+Pen+Script&display=swap');
p {
            color: darksalmon;
            text-align: center;
            line-height:200%;
            /*
			text-decoration: line-through;
			*/

            font-size: 48px;
            font-weight: bold;
            font-family: 'Black And White Picture', sans-serif;
}
</style>

<p>
	맘대로 못 지웁니다~
</p>

<%= link_to "back", posts_index_path %>

app/views/posts/edit.html.erb
<% if user_signed_in? && current_user.email == "aaa@aaa.aaa" %>

<form action="/posts/update/<%= @post.id %>" method="POST">
	<input name="title" type="text" value="<%= @post.title %>">
	<br />
	<textarea name="content"><%= @post.content %></textarea>
	<button>
		Edit
	</button>
</form>

<p>
	<%= link_to "back", :back %>	
</p>

<% else %>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Jua&family=Kirang+Haerang&family=Nanum+Pen+Script&display=swap');
</style>

<p>
	<font face="'Jua', sans-serif" size=100px>수정 권한 노노~❤️ </font>
</p>

<%= link_to "back", posts_index_path %>

<% end %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
	<p><%= current_user.email %>, hello</p>
	<p><%= link_to "logout", destroy_user_session_path, method: :delete %></p>
	<hr style="border:solid 2px #9400D3">
<% else %>
	<p><a href="/users/sign_in">login-1</a> &nbsp;
		<%= link_to "login-2", user_session_path %></p>
	<hr size="2px">
<% end %>

<% if user_signed_in? %>
<p><%= current_user.created_at %></p>
<% end %>

<a href="/posts/new">공지글쓰기</a> &nbsp;&nbsp;&nbsp; 
<span> <a href="/blogs">한문장일기(1文章日記)</a> &nbsp;&nbsp;&nbsp; </span>
<span> <a href="/weedocs/index">Weedoc위독</a> &nbsp;&nbsp;&nbsp; </span>
<span> <a href="/bang.html">방선생화실</a> &nbsp;&nbsp;&nbsp; </span>
<span> <a href="/practices/kanji">12간지 연애유형(十二支恋愛類型)</a> &nbsp;&nbsp;&nbsp; </span>

<hr style="border:solid 3px #228B22">

<div class="notice_index">
	<div class="notice">
		<table border="1">
			<tr>
				<th>id</th>
				<th>title</th>
				<th>content</th>
				<th>create time</th>
				<!--th>modify time</th-->
				<th>link</th>
				<!--th>writer</th-->
			</tr>
			<% @posts.each do |post| %>
			<tr>
				<td><%= post.id %></td>
				<td><%= post.title %></td>
				<td><%= post.content %></td>
				<td><%= post.created_at %></td>
				<!--td><%= post.updated_at %></td-->
				<td><a href="/posts/show/<%= post.id %>">show</a>
					<a href="/posts/edit/<%= post.id %>">edit</a>
					<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/posts/destroy/<%= post.id %>">delete</a>
					<!--%= link_to "delete2",xxx, method: :delete, data: { confirm: "Are you sure?"} %></td -->
				<!--td><%= post.writer %></td-->
			</tr>
			<% end %>
		</table>
	</div>
	
	
	<div class="memopaper" onmouseleave="memoOut()" >
		<div>
			<label onclick="memoshow(this)" >💡Memo📌</label>
			<hr />
		</div>
		<div class="memo" id="memo" onclick="memowrite(this)">
			<lable id="memo2"><% memo = File.open("public/memo.txt", "r+") %><% memo.each do |line| %><%= line.chomp %><br>
<% end %><%	memo.close %></lable>
		</div>
		<div >
			<center><textarea name="memoContent" id="memoContent" style="display: none; width:280px; height:210px; "></textarea></center>
			<br>
			<center><input type="button" id="memoButton" onclick="memoButton()"  style="display: none;" value="ok"></center>
		</div>
		
	</div>
</div>


<script type="text/javascript">
			function memoOut(){
				if( document.getElementById("memoContent").style.display == 'block'){
					document.getElementById("memo").style.display ='block';
					document.getElementById("memoContent").style.display ='none';
					document.getElementById("memoButton").style.display ='none';	
				}			
				
			}
		
			function memowrite(){
				if(document.getElementById("memoContent").style.display == 'none'){
					document.getElementById("memo").style.display ='none';
					document.getElementById("memoContent").style.display ='block';
					document.getElementById("memoButton").style.display ='block';
					document.getElementById("memoContent").value = document.getElementById("memo2").innerText;
				} else{
					document.getElementById("memoContent").style.display ='none';		
				}
			}
	
			function memoshow(){
				if(document.getElementById("memo").style.display == 'none'){
					document.getElementById("memo").style.display ='block';			
				} else{
					document.getElementById("memo").style.display ='none';	
				}
			}
	
			function memoButton(e){
				document.getElementById("memo").style.display ='block';
				document.getElementById("memo").innerText = document.getElementById("memoContent").value;
				
				document.getElementById("memoContent").style.display ='none';
				document.getElementById("memoButton").style.display ='none';
				
				
			}
	
</script>
		

app/views/posts/new.html.erb
<link rel="stylesheet" href="new.css">

<form action="/posts/create" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<label for="title">제목</label>
	<input name="title" type="text" id="title" size="15">
	<br />
	<label for="content">내용</label>
	<textarea name="content" id="content"></textarea>
	<br />
	<button>
		submit
	</button>
	
	<input type="password" name="post_pw">
	<input type="radio" name="scret" value="1">
	<input type="radio" name="scret" value="2">
	<input type="radio" name="scret" value="3">
	<button type="reset"> reset </button>
	<br />
	<label for="Korean">한국어<input type="checkbox" name="language" id="Korean"></label>
    <label for="Japan">日本語<input type="checkbox" name="language" id="Japan"></label>
    <label for="English">English<input type="checkbox" name="language"></label>
    <label for="France">Français<input type="checkbox" name="language"></label>
	
	<div class="boxes">
		<div class="box">1</div>
		<div class="box">2</div>
		<div class="box">3</div>
		<div class="box">4</div>
		<div class="box">5</div>
	</div>
</form>
<p>
	<%= link_to "back", :back %>	
</p>

app/views/posts/show.html.erb
<h1>글쓴거 확인</h1>


title : <%= @post.title %>
<br />
content : <%= @post.content %>
<br />
<a href="/posts/index">back</a>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>