config/routes.rb
Rails.application.routes.draw do
  get 'practices/kanji'
	get 'practices/result' => "practices#result"
	post 'practices/add' => "practices#add"
	delete 'practices/delete/:id' => "practices#delete"
	
  get 'weedocs/index' => "weedocs#index"
  get 'weedocs/add'
	post 'weedocs/add' => "weedocs#create"
	get 'weedocs/delete'
	get 'weedocs/search' => "weedocs#search"
  delete 'weedocs/delete/:id' => "weedocs#delete"
	
  resources :blogs do
	  resources :comments
  end
	
  devise_for :users
	root "posts#index"
  get 'posts/index'
  get 'posts/new' => "posts#new"
  post 'posts/create' => "posts#create"
  get 'posts/show/:id' => "posts#show"
  get 'posts/edit/:ids' => "posts#edit"
  post 'posts/update/:id' => "posts#update"
  #get 'posts/destroy/:id' => "posts#destroy"
	delete 'posts/destroy/:id' => "posts#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	
	post "blogs/:blog_id/likes/create" => "likes#create"
	post "blogs/:blog_id/likes/destroy" => "likes#destroy"
	
	# post하면 토큰이 필요하네. get하면 https에서 http로 자동으로 가버리네?
	#get "blogs/:blog_id/likes/create" => "likes#create"
	#get "blogs/:blog_id/likes/destroy" => "likes#destroy"
	
	
end

app/models/weedoc.rb
class Weedoc < ApplicationRecord
end

app/controllers/weedocs_controller.rb
class WeedocsController < ApplicationController
	before_action :set_weedoc, only: [:delete]
	
  def index
	  @weedocs = Weedoc.all
  end

  def add
	 @weedoc = Weedoc.new
	  
  end

	def create
		@weedoc = Weedoc.new(weedoc_params)
	
		respond_to do |format|
      		if @weedoc.save
				format.html { redirect_to weedocs_index_path, notice: 'successfully created.' }
				#format.json { render :show, status: :created, location: @blog }
			else
				format.html { render :new }
				#format.json { render json: @blog.errors, status: :unprocessable_entity }
			end
		end
	end
	
  def delete
	  @weedoc.destroy
	  
  end
	
	def search
		 @wee_category = Weedoc.select(:category).distinct 
		 @wee_organ = Weedoc.where(category: params[:category]).select(:organ, :category).distinct
		 @wee_sign1 = Weedoc.where(category: params[:category], organ: params[:organ]).select(:sign1, :organ).distinct
		 @wee_sign2 = Weedoc.where(category: params[:category], organ: params[:organ], sign1: params[:sign1]).select(:sign2,:sign1, :organ).distinct
		 @wee_strong = Weedoc.where(category: params[:category], organ: params[:organ], sign1: params[:sign1], sign2: params[:sign2]).select(:strong,:sign2,:sign1, :organ).distinct
		 @wee_cause = Weedoc.where(category: params[:category], organ: params[:organ], sign1: params[:sign1], sign2: params[:sign2],strong: params[:strong]).select(:cause, :expect,:strong,:sign2,:sign1, :organ)
		 @wee_expect = Weedoc.where(cause: params[:cause]).select(:expect).distinct
		 @wee_hash = weedoc_course
	end
	
	private 
	def set_weedoc
		@weedoc = Weedoc.find(params[:id])
	end
	
	def weedoc_params
		params.require(:weedoc).permit(:category, :organ, :sign1, :sign2, :strong, :cause, :expect)
	end
	
	def weedoc_course
		if !@wee_hash
			@wee_hash={}
		else
			wee_hash = @wee_hash
			if params
				wee_hash[:category] = params[:category]
				wee_hash[:organ] = params[:organ]
				wee_hash[:sign1] = params[:sign1]
				wee_hash[:sign2] = params[:sign2]
				wee_hash[:strong] = params[:strong]
			end
		end
		return wee_hash
	end
		
end

app/helpers/weedocs_helper.rb
module WeedocsHelper
end

app/views/weedocs/_form.html.erb
<%= form_with(model: @weedoc, url: weedocs_add_path) do |form| %>


  <div class="field">
    <%= form.label :category, "대분류" %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :organ, "기관" %>
    <%= form.text_field :organ %>
  </div>

  <div class="field">
    <%= form.label :sign1, "증상1" %>
    <%= form.text_field :sign1 %>
  </div>

  <div class="field">
    <%= form.label :sign2, "증상2" %>
    <%= form.text_field :sign2 %>
  </div>
  
  <div class="field">
    <%= form.label :strong, "강도" %>
    <%= form.text_field :strong %>
  </div>

  <div class="field">
    <%= form.label :cause, "원인" %>
    <%= form.text_field :cause %>
  </div>

  <div class="field">
    <%= form.label :expect, "예상" %>
    <%= form.text_field :expect %>
  </div>


  <div class="actions">
    <%= form.submit "작성(作成)"%>
  </div>
<% end %>

app/views/weedocs/add.html.erb
<h1>Weedocs#add</h1>
<p>Find me in app/views/weedocs/add.html.erb</p>


<%= render 'form', weedoc: @weedoc %>


<%= link_to "Back", :back %>

app/views/weedocs/delete.html.erb
<h1>Weedocs#delete</h1>
<p>Find me in app/views/weedocs/delete.html.erb</p>

<%= link_to "Back", :back %>

app/views/weedocs/index.html.erb
<style>
	.weedoc{
            display: grid;
			/* grid-template-columns: repeat(2, 300px); */
            /* grid-template-rows: repeat(5, 50px); */
			/* background-color: pink; */

            /* justify-items: center; */
            /* align-items: center; */
            
            /* justify-content: center; */
            /* align-content: center; */
            /* height: 100vh; */
        }
	.weedoc div{
			border: 1px solid pink;
	}
	
	.cause{
		grid-column: 2/span 2;
		grid-row: 1/span 2
	}
	
	.expect{
		grid-column: 2/span 2;
		grid-row: 3/span 4
		
	}
</style>

<h1>어디가 아프십니까??</h1>
<br />
<%= link_to "HOME", root_path  %>
<br />
<hr />
<div>
	rails g model Weedoc category organ sign1 sign2 strong cause expect
</div>
<div>
	cloud IDE장애 생기면, 아무것도 못하네. 로컬 리눅스를 사용하는 걸 익숙해져야겠다.
</div>
<%= link_to "추가", weedocs_add_path %>  &nbsp;&nbsp;
<!--<%= link_to "삭제", weedocs_delete_path %>-->
<br />


<div class="weedoc">
	<div class="show"><iframe src="search.html" name="weedoc" width="100%" height="100%" frameborder="0" scrolling="no"marginwidth="0" marginheight="0"></iframe></div>	
</div>



<script type="text/javascript">

</script>

<br />
<br />
<br />
<br />
<br />
<hr />

<button onclick=dbshow()>db</button>
<div id="dbtable" style="display: none;">
<table border=1>
  <head>
    <tr>
	  <th>번호</th>
	  <th>id</th>
	  <th>대분류</th>
      <th>기관</th>
	  <th>증상1</th>
	  <th>증상2</th>
	  <th>강도</th>
	  <th>원인</th>
	  <th>예상</th>
    </tr>
  </head>

  <body>
    <% @weedocs.each_with_index do |weedoc, index| %>
      <tr>
		<td><%= index+1 %></td>
		<td><%= weedoc.id %></td>
		<td><%= weedoc.category %></td>
        <td><%= weedoc.organ %></td>
		<td><%= weedoc.sign1 %></td>
		<td><%= weedoc.sign2 %></td>
		<td><%= weedoc.strong %></td>
		<td><%= weedoc.cause %></td>
		<td><%= weedoc.expect %></td>
		<td><%= link_to("delete", "/weedocs/delete/#{weedoc.id}", method: :delete, data: { confirm: "delete?"}) %></td>
    <% end %>
  </body>
</table>
</div>

<script type="text/javascript">
	function dbshow(){
		if (document.getElementById("dbtable").style.display == 'block')
			document.getElementById("dbtable").style.display ='none';
		else
			document.getElementById("dbtable").style.display ='block';
		
	}
</script>

app/views/weedocs/index.html_20220313.erb
개삽질의 흔적 시발...
결국 iframe으로 하다니...이게 맞나 싶네

<style>
	.weedoc{
            display: grid;
			grid-template-columns: repeat(2, 300px);
            grid-template-rows: repeat(5, 50px);
			background-color: pink;

            gap: 1;
            /* justify-items: center; */
            /* align-items: center; */
            
            /* justify-content: center; */
            /* align-content: center; */
            /* height: 100vh; */
        }
	.weedoc div{
			border: 1px solid black;
	}
	
	.cause{
		grid-column: 2/span 2;
		grid-row: 1/span 2
	}
	
	.expect{
		grid-column: 2/span 2;
		grid-row: 3/span 4
		
	}
</style>

<h1>어디가 아프십니까??</h1>
<br />
<%= link_to "HOME", root_path  %>
<br />
<hr />
<div>
	rails g model Weedoc category organ sign1 sign2 strong cause expect
</div>
<%= link_to "추가", weedocs_add_path %>  &nbsp;&nbsp;
<!--<%= link_to "삭제", weedocs_delete_path %>-->
<br />

<!--
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
검색

-대분류: 내장, 뼈/근육
-기관
-증상1
-증상2
-강도
-원인
-예상


검색 -대분류: 내장, 뼈/근육 -기관 -증상1 -증상2 -강도 -원인 -예상
rails g model Weedoc category organ sign1 sign2 strong cause expect
<hr />

<% @weedocs.each do |weedoc| %>
	<%= weedoc.id %>
	<br>
	<%= weedoc.category%>
	<br>
<% end %>

<select>
	<% @weedocs.each do |weedoc| %>
	<option value="<%= weedoc.id %>"> <%= weedoc.category %></option>
	<% end %>
</select>
	

<% def wow1 a,b 
	c = a + b
	return c
end %>
	<%= @weedocs.size %>
, 
<%= @weedocs.class %>
<br>
%%%%%%
<br>
<%= Weedoc.where(id: 3) %>
<%= Weedoc.find(3).category %>
<br>
******
<br >
<%= @wee2 = Weedoc.select(:category).distinct %>
<% @wee2.each do |weedoc| %>
	<%= weedoc.category%>
	<br>
<% end %>
<%= @wee2.class %>
<hr >
<%= @wee3 = Weedoc.where(category: "내장").select(:sign1).distinct %>
<br >
$$$$$$$$$$$$$
<%= @wee3[0].sign1 %>
<br >
<% @wee3.each do |weedoc| %>
	<%= weedoc.sign1%>
	<br>
<% end %>

<br >
<%= Weedoc.where(id: 3).to_sql %>
<hr >
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-->
<div id='result'>
	a	
</div>
<div id='result2'>
	aa
</div>


<select id="select_cat" onchange="selectCat(this)">
	<option value="" selected disabled>--대분류--</option>
	<% @wee_cat = Weedoc.select(:category).distinct %>
	<% @wee_cat.each do |weedoc| %>
	<option value="category"><%= weedoc.category %></option>
	<% end %>
</select>



<select class="select_org" onmouseout="" onchange="selectOrg(this)">
	<option value="" selected disabled>--기관--</option>
</select>


<select class="select_sign1" onchange="selectSign1(this)">
	<option value="" selected disabled>--증상1--</option>
</select>


<select class="select_sign2" onchange="selectSign2(this)">
	<option value="" selected disabled>--증상2--</option>
</select>


<select class="select_sign1" onchange="selectSign(this)">
	<option value="" selected disabled>--강도--</option>
</select>




<div class="weedoc">
	<div class="category"><iframe src="search.html" name="b"  width="100%" height="100%" frameborder="0" scrolling="no"marginwidth="0" marginheight="0"></iframe></div>
	<div class="organ"><iframe src="search.html#222" name="c"  width="100%" height="100%" frameborder="0" scrolling="no"marginwidth="0" marginheight="0"></iframe></div>
	<div class="sign1"><iframe name="d"  width="100%" height="100%" frameborder="0" scrolling="no"marginwidth="0" marginheight="0"></iframe></div>
	<div class="sing2">증상2</div>
	<div class="strong">강도</div>
	<div class="cause">원인</div>	
	<div class="expect"><iframe src="search.html" name="b"  width="100%" height="100%" frameborder="0" scrolling="no"marginwidth="0" marginheight="0"></iframe></div>	
</div>

<!-- 문자열로 자바스크립트로 넘겨줘서 할 생각을 하다니...지금 보니 참...안 좋은 선택이었네
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
<% def db_export(str)
	
	@wee5 = Weedoc.where(category: str).select(:organ).distinct
	arr = []
	brr = "[ 선택 "
	@wee5.each do |weedoc|
		arr << weedoc.organ
		brr = brr + ", " + " \"#{weedoc.organ}\" "
	end
	brr = brr + "]"
	return brr
	
end %>
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-->

<script type="text/javascript">
	function selectCat(e){
		//var catSelect = document.getElementById("select_cat");
		//var selectText = catSelect.options[catSelect.selectedIndex].text;
		
		var selectCat = e.options[e.selectedIndex].text;
		
		document.getElementById('result2').innerText = "<%= db_export(@wee_cat[1].category) %>"
		
		switch(selectCat){
			<% @wee_cat.each do | weedoc |  %>
			case '<%= weedoc.category %>' :
				
				var subOption = [ '--기관--' <% Weedoc.where(category: weedoc.category).select(:organ).distinct.each do | wee | %>
									,'<%= wee.organ %>'
									<% end %> ];
				break;
			<% end %>

		}
			
		var select = document.querySelector('.select_org')

		select.options.length = 0;
		var option = document.createElement('option');
		//option.innerText = "---HHH---";
		option.select = 0;
		//select.append(option);
		
		document.getElementById('result').innerText = subOption[2];
		
		for (var i = 0; i < subOption.length; i++){
			var option = document.createElement('option');
			option.innerText = subOption[i];
			select.append(option);
		}
	}
	
	
	function selectOrg(e){
		// 20220312 
		// 안되는걸 알고 gg 친다. 자바스크립트도 결국 html과 같이 그 안에서 움직임은 동적이라고 할 수 있으나, 내용은 정적이네.
		// 그 말은....처음에 로딩된 값으로만 동적으로 움직이는거네. 자바스크립트로 다시 값을 가져와서 바꾸려고 하면 안 바뀌네...
		// 처음에 불러 온 값 중에 어느 것으로 변경되는건 가능하나, 완전히 새로운 값을 가져오거나 바꾸는건 안되네...
		// 흠...대분류 -> 기관 으로 찾는 흐름도 결국 처음에 로딩한 값 중에 선택이 되는거지, 그 값을 새로이 불러와서 보여주는건 아니었네
		// 결국 하나씩 검색할때마다 get으로 페이지 주고 받아야 하는건가?
		
		var selectOrg2 = e.options[e.selectedIndex].text;
		document.getElementById('result2').innerText = selectOrg2;
		
		<% @wee_org = Weedoc.select(:organ).distinct %>
		switch(selectOrg2){
			<% @wee_org.each do | weedoc | %>
			case '<%= weedoc.organ %>':
				var subOption = [ '-증상1-' <% Weedoc.where(category: weedoc.organ).select(:sign1).distinct.each do | wee | %>
									,'<%= wee.sign1 %>'
									<% end %> ];
				break;
			<% end %>
		}

		
		var select = document.querySelector('.select_sign1')

		
		select.options.length = 0;
		var option = document.createElement('option');
		option.select = 0;
		
		document.getElementById('result').innerText = subOption.length;
		
		for (var i = 0; i < subOption.length; i++){
			var option = document.createElement('option');
			option.innerText = subOption[i];
			select.append(option);
		}
		
	}
	
	

</script>

<br />
<br />
<br />
<br />
<br />
<hr />

<table border=1>
  <head>
    <tr>
	  <th>번호</th>
	  <th>id</th>
	  <th>대분류</th>
      <th>기관</th>
	  <th>증상1</th>
	  <th>증상2</th>
	  <th>강도</th>
	  <th>원인</th>
	  <th>예상</th>
    </tr>
  </head>

  <body>
    <% @weedocs.each_with_index do |weedoc, index| %>
      <tr>
		<td><%= index+1 %></td>
		<td><%= weedoc.id %></td>
		<td><%= weedoc.category %></td>
        <td><%= weedoc.organ %></td>
		<td><%= weedoc.sign1 %></td>
		<td><%= weedoc.sign2 %></td>
		<td><%= weedoc.strong %></td>
		<td><%= weedoc.cause %></td>
		<td><%= weedoc.expect %></td>
		<td><%= link_to("delete", "/weedocs/delete/#{weedoc.id}", method: :delete, data: { confirm: "delete?"}) %></td>
    <% end %>
  </body>
</table>

app/views/weedocs/search.html.erb
<select id="select_cat" onchange="window.open(value, '_self');">
	<option selected disabled>--대분류--</option>
	<% @wee_category.each do |weedoc| %>
	<option value="?category=<%=weedoc.category%>" <%= "selected" if params[:category] == weedoc.category %> > <%= weedoc.category %> </option>
	<% end %>
</select>



<select id="select_organ" onchange="window.open(value, '_self');">
	<option selected disabled>--<%= params[:organ] ? params[:organ] : "기관"%>--</option>
	<% @wee_organ.each do |weedoc| %>
	<option value="?organ=<%=weedoc.organ%>&category=<%=params[:category]%>"> <%= weedoc.organ %> </option>
	<% end %>
</select>


<select id="select_sign1" onchange="window.open(value, '_self');">
	<option selected disabled>--<%= params[:sign1] ? params[:sign1] : "증상1"%>--</option>
	<% @wee_sign1.each do |weedoc| %>
	<option value="?sign1=<%=weedoc.sign1%>&organ=<%=weedoc.organ%>&category=<%=params[:category]%>"> <%= weedoc.sign1 %> </option>
	<% end %>
</select>

<select id="select_sign2" onchange="window.open(value, '_self');">
	<option selected disabled>--<%= params[:sign2] ? params[:sign2] : "증상2"%>--</option>
	<% @wee_sign2.each do |weedoc| %>
	<option value="?sign2=<%=weedoc.sign2%>&sign1=<%=weedoc.sign1%>&organ=<%=weedoc.organ%>&category=<%=params[:category]%>"> <%= weedoc.sign2 %> </option>
	<% end %>
</select>

<select id="select_strong" onchange="window.open(value, '_self');">
	<option selected disabled>--<%= params[:strong] ? params[:strong] : "강도"%>--</option>
	<% @wee_strong.each do |weedoc| %>
	<option value="?strong=<%=weedoc.strong%>&sign2=<%=weedoc.sign2%>&sign1=<%=weedoc.sign1%>&organ=<%=weedoc.organ%>&category=<%=params[:category]%>"> <%= weedoc.strong %> </option>
	<% end %>
</select>



<!--
<br>
<% if @wee_hash %>
<%= @wee_hash.each_value { |v| v } %>
<% end %>

<br>

<% @wee_organ.each do |weedoc| %>
	<%= weedoc.organ %>
<% end %>
		 
		<% @wee_sign1.each do |weedoc| %>
			<%= weedoc.sign1 %>
		<% end %>

		<% @wee_sign2.each do |weedoc| %>
			<%= weedoc.sign2 %>
		<% end %>

		<% @wee_strong.each do |weedoc| %>
			<%= weedoc.strong %>
		<% end %>

-->

<br>
<hr>
		<% @wee_cause.each do |weedoc| %>
			원인 : <%= weedoc.cause %><br><hr>
			의심 : <%= weedoc.expect %>
		<% end %>

<br>
<hr>

<!--
개삽질의 현장... 
전에도 썼지만, html도 javascript도 일단 한번 가져온 값에 안 에서만 동적으로 움직이는걸 알았다.
새로 값을 가져오거나 그러기 위해선 페이지간의 속성값의 주고받음이 필요하네.
이걸 몰라서 어찌저찌 하겠다고 개 삽질 ㅠㅠ

<select id="select_cat" onchange="selectCat(this)">
	<option value="" selected disabled>--대분류--</option>
	<% @wee_cat = Weedoc.select(:category).distinct %>
	<% @wee_cat.each do |weedoc| %>
	<option value="category"><%= weedoc.category %></option>
	<% end %>
</select>


<select id="select_organ" onchange="window.open(value, '_self');">
	<option selected disabled>--기관텍스트--</option>
	<option value="?organ=폐">폐</option>
	<option value="?organ=발뒤꿈치">발뒤꿈치</option>
	<option value="?organ=손가락">손가락</option>
	<option value="?organ=위">위</option>
</select>

<br>
<hr>
-->

<!-- 레일즈 헬퍼...이것만 잘 써도 좋을거 같은데..흠..아직 멀었따. -->
<!-- %= collection_select(:weedoc, :category, @weedocs, :id, :category) %> -->

<!-- <select name="category[organ]" id="category_organ"><option value="3">숨 쉴때 쿡쿡 아프다.</option>  -->
<!-- %= collection_select(:category, :organ, @weedocs, :id, :sign1) %> -->